<?php
declare(strict_types=1);

namespace App\Config;

final class ModuleRegistry
{
    public static function all(): array
    {
        return [
            'users' => [
                'table' => 'users',
                'title' => 'modules.users',
                'roles' => ['admin'],
                'creator' => false,
                'fields' => [
                    'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name'],
                    'name' => ['type' => 'text', 'label' => 'fields.name_en', 'required' => true],
                    'email' => ['type' => 'email', 'label' => 'fields.email'],
                    'mobile' => ['type' => 'text', 'label' => 'fields.mobile'],
                    'password' => ['type' => 'password', 'label' => 'fields.password', 'required' => true],
                    'role' => ['type' => 'select', 'label' => 'fields.role', 'options' => ['admin', 'foreman', 'labor'], 'required' => true],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['active', 'inactive', 'suspended'], 'required' => true],
                    'language' => ['type' => 'select', 'label' => 'app.language', 'options' => ['en', 'bn'], 'required' => true],
                    'theme' => ['type' => 'select', 'label' => 'app.theme', 'options' => ['light', 'dark'], 'required' => true],
                ],
            ],
            'roles' => [
                'table' => 'roles',
                'title' => 'modules.roles',
                'roles' => ['admin'],
                'creator' => false,
                'fields' => [
                    'name' => ['type' => 'text', 'label' => 'fields.name_en', 'required' => true],
                    'label_en' => ['type' => 'text', 'label' => 'fields.label_en', 'required' => true],
                    'label_bn' => ['type' => 'text', 'label' => 'fields.label_bn'],
                ],
            ],
            'workers' => [
                'table' => 'workers',
                'title' => 'modules.workers',
                'roles' => ['admin'],
                'financial' => false,
                'fields' => [
                    'photo_path' => ['type' => 'file', 'label' => 'fields.photo'],
                    'id_number' => ['type' => 'text', 'label' => 'fields.id_number', 'readonly' => true],
                    'full_name' => ['type' => 'text', 'label' => 'fields.full_name', 'required' => true],
                    'full_name_bn' => ['type' => 'text', 'label' => 'fields.full_name_bn'],
                    'father_name' => ['type' => 'text', 'label' => 'fields.father_name'],
                    'nid' => ['type' => 'text', 'label' => 'fields.nid'],
                    'date_of_birth' => ['type' => 'date', 'label' => 'fields.date_of_birth'],
                    'age' => ['type' => 'number', 'label' => 'fields.age'],
                    'address' => ['type' => 'textarea', 'label' => 'fields.address'],
                    'blood_group' => ['type' => 'select', 'label' => 'fields.blood_group', 'options' => ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']],
                    'mobile' => ['type' => 'text', 'label' => 'fields.mobile', 'required' => true],
                    'password' => ['type' => 'password', 'label' => 'fields.password'],
                    'joining_date' => ['type' => 'date', 'label' => 'fields.joining_date'],
                    'skill' => ['type' => 'text', 'label' => 'fields.skill'],
                    'daily_salary' => ['type' => 'money', 'label' => 'fields.daily_salary', 'required' => true],
                    'role' => ['type' => 'select', 'label' => 'fields.role', 'options' => ['foreman', 'labor', 'supervisor', 'mistry', 'helper', 'welder', 'engineer'], 'required' => true],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['active', 'suspended', 'inactive'], 'required' => true],
                ],
            ],
            'projects' => [
                'table' => 'projects',
                'title' => 'modules.projects',
                'roles' => ['admin', 'foreman'],
                'financial' => false,
                'fields' => [
                    'name_en' => ['type' => 'text', 'label' => 'fields.project_name_en', 'required' => true],
                    'name_bn' => ['type' => 'text', 'label' => 'fields.project_name_bn'],
                    'client_name' => ['type' => 'text', 'label' => 'fields.client_name', 'required' => true],
                    'client_mobile' => ['type' => 'text', 'label' => 'fields.client_mobile'],
                    'location' => ['type' => 'text', 'label' => 'fields.location'],
                    'work_type_en' => ['type' => 'text', 'label' => 'fields.work_type_en'],
                    'work_type_bn' => ['type' => 'text', 'label' => 'fields.work_type_bn'],
                    'start_date' => ['type' => 'date', 'label' => 'fields.start_date'],
                    'expected_end_date' => ['type' => 'date', 'label' => 'fields.expected_end_date'],
                    'total_amount' => ['type' => 'money', 'label' => 'fields.total_amount', 'required' => true],
                    'description_en' => ['type' => 'textarea', 'label' => 'fields.description_en'],
                    'description_bn' => ['type' => 'textarea', 'label' => 'fields.description_bn'],
                    'project_attachment_path' => ['type' => 'attachment', 'label' => 'fields.project_attachment'],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['planning', 'running', 'completed', 'cancelled'], 'required' => true],
                ],
            ],
            'worker-projects' => [
                'table' => 'worker_projects',
                'title' => 'modules.worker_projects',
                'roles' => ['admin', 'foreman'],
                'fields' => [
                    'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name', 'required' => true],
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'start_date' => ['type' => 'date', 'label' => 'fields.start_date', 'required' => true],
                    'end_date' => ['type' => 'date', 'label' => 'fields.end_date'],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['active', 'completed', 'paused'], 'required' => true],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                ],
            ],
            'attendance' => [
                'table' => 'attendance',
                'title' => 'modules.attendance',
                'roles' => ['admin', 'foreman', 'labor'],
                'financial' => true,
                'fields' => [
                    'attendance_date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name', 'required' => true],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['present', 'absent', 'half_day', 'leave', 'holiday'], 'required' => true],
                    'overtime_hours' => ['type' => 'number', 'label' => 'fields.overtime_hours'],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                ],
            ],
            'salary' => [
                'table' => 'salary_transactions',
                'title' => 'modules.salary',
                'roles' => ['admin', 'foreman', 'labor'],
                'read_only' => true,
                'fields' => [
                    'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name'],
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en'],
                    'transaction_date' => ['type' => 'date', 'label' => 'fields.date'],
                    'type' => ['type' => 'select', 'label' => 'fields.type', 'options' => ['salary', 'bonus', 'deduction', 'adjustment']],
                    'amount' => ['type' => 'money', 'label' => 'fields.amount'],
                    'overtime_amount' => ['type' => 'money', 'label' => 'dashboard.overtime'],
                    'description' => ['type' => 'textarea', 'label' => 'fields.description'],
                ],
            ],
            'advances' => self::moneyModule('advances', 'modules.advances', ['worker_id', 'date', 'project_id', 'amount', 'reason', 'notes', 'status'], ['approved', 'void'], ['admin', 'foreman']),
            'withdrawals' => self::moneyModule('withdrawals', 'modules.withdrawals', ['worker_id', 'date', 'project_id', 'amount', 'payment_method', 'reference', 'notes', 'status'], ['paid', 'void']),
            'bonuses' => self::moneyModule('bonuses', 'modules.bonuses', ['worker_id', 'date', 'project_id', 'amount', 'description', 'status'], ['approved', 'void']),
            'deductions' => self::moneyModule('deductions', 'modules.deductions', ['worker_id', 'date', 'project_id', 'amount', 'description', 'status'], ['active', 'void']),
            'leave' => [
                'table' => 'leave_applications',
                'title' => 'modules.leave',
                'roles' => ['admin', 'foreman', 'labor'],
                'fields' => [
                    'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name'],
                    'leave_type' => ['type' => 'select', 'label' => 'fields.leave_type', 'options' => ['sick', 'casual', 'emergency', 'annual'], 'required' => true],
                    'start_date' => ['type' => 'date', 'label' => 'fields.start_date', 'required' => true],
                    'end_date' => ['type' => 'date', 'label' => 'fields.end_date', 'required' => true],
                    'reason' => ['type' => 'textarea', 'label' => 'fields.reason', 'required' => true],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['pending', 'approved', 'rejected', 'cancelled']],
                    'admin_note' => ['type' => 'textarea', 'label' => 'fields.admin_note'],
                ],
            ],
            'expenses' => self::expenseModule('expenses', 'modules.expenses'),
            'materials' => [
                'table' => 'material_purchases',
                'title' => 'modules.materials',
                'roles' => ['admin', 'foreman'],
                'financial' => true,
                'fields' => [
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'material' => ['type' => 'text', 'label' => 'fields.material', 'required' => true],
                    'quantity' => ['type' => 'number', 'label' => 'fields.quantity', 'required' => true],
                    'unit' => ['type' => 'text', 'label' => 'fields.unit'],
                    'unit_price' => ['type' => 'money', 'label' => 'fields.unit_price', 'required' => true],
                    'carrying_cost' => ['type' => 'money', 'label' => 'fields.carrying_cost'],
                    'supplier' => ['type' => 'text', 'label' => 'fields.supplier'],
                    'invoice_image' => ['type' => 'file', 'label' => 'fields.invoice_image'],
                    'purchase_date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
                ],
            ],
            'food' => [
                'table' => 'food_expenses',
                'title' => 'modules.food',
                'roles' => ['admin', 'foreman'],
                'financial' => true,
                'fields' => [
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'food_item' => ['type' => 'text', 'label' => 'fields.food_item', 'required' => true],
                    'carrying_cost' => ['type' => 'money', 'label' => 'fields.carrying_cost'],
                    'total_cost' => ['type' => 'money', 'label' => 'fields.total_cost', 'required' => true],
                    'description' => ['type' => 'textarea', 'label' => 'fields.description'],
                    'expense_date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
                ],
            ],
            'vehicles' => [
                'table' => 'vehicle_expenses',
                'title' => 'modules.vehicles',
                'roles' => ['admin', 'foreman'],
                'financial' => true,
                'fields' => [
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'vehicle_type' => ['type' => 'text', 'label' => 'fields.vehicle_type'],
                    'driver_name' => ['type' => 'text', 'label' => 'fields.driver_name'],
                    'rental_amount' => ['type' => 'money', 'label' => 'fields.rental_amount'],
                    'fuel_amount' => ['type' => 'money', 'label' => 'fields.fuel_amount'],
                    'other_cost' => ['type' => 'money', 'label' => 'fields.other_cost'],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                    'expense_date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
                ],
            ],
            'payments' => [
                'table' => 'received_payments',
                'title' => 'modules.payments',
                'roles' => ['admin'],
                'financial' => true,
                'fields' => [
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'client_name' => ['type' => 'text', 'label' => 'fields.client_name'],
                    'received_amount' => ['type' => 'money', 'label' => 'fields.received_amount', 'required' => true],
                    'payment_date' => ['type' => 'date', 'label' => 'fields.payment_date', 'required' => true],
                    'payment_method' => ['type' => 'select', 'label' => 'fields.payment_method', 'options' => ['cash', 'bank', 'mobile_banking', 'cheque', 'other']],
                    'cheque_number' => ['type' => 'text', 'label' => 'fields.cheque_number'],
                    'cheque_image' => ['type' => 'file', 'label' => 'fields.cheque_image'],
                    'bank_name' => ['type' => 'text', 'label' => 'fields.bank_name'],
                    'transaction_reference' => ['type' => 'text', 'label' => 'fields.reference'],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['received', 'cancelled']],
                ],
            ],
            'equipment' => [
                'table' => 'equipment',
                'title' => 'modules.equipment',
                'roles' => ['admin'],
                'fields' => [
                    'name_en' => ['type' => 'text', 'label' => 'fields.name_en', 'required' => true],
                    'name_bn' => ['type' => 'text', 'label' => 'fields.name_bn'],
                    'category' => ['type' => 'text', 'label' => 'fields.category'],
                    'quantity' => ['type' => 'number', 'label' => 'fields.quantity', 'required' => true],
                    'purchase_price' => ['type' => 'money', 'label' => 'fields.purchase_price'],
                    'condition_status' => ['type' => 'select', 'label' => 'fields.condition', 'options' => ['available', 'assigned', 'damaged', 'under_repair', 'cancelled', 'lost']],
                    'location' => ['type' => 'text', 'label' => 'fields.location'],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                ],
            ],
            'equipment-assignments' => [
                'table' => 'equipment_assignments',
                'title' => 'modules.equipment_assignments',
                'roles' => ['admin'],
                'fields' => [
                    'equipment_id' => ['type' => 'relation', 'label' => 'fields.equipment', 'source' => 'equipment', 'display' => 'name_en', 'required' => true],
                    'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                    'quantity' => ['type' => 'number', 'label' => 'fields.quantity', 'required' => true],
                    'issue_date' => ['type' => 'date', 'label' => 'fields.issue_date', 'required' => true],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['assigned', 'returned', 'damaged', 'cancelled']],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                ],
            ],
            'admin-expenses' => [
                'table' => 'admin_personal_expenses',
                'title' => 'modules.admin_expenses',
                'roles' => ['admin'],
                'financial' => true,
                'fields' => [
                    'expense_date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
                    'category' => ['type' => 'text', 'label' => 'fields.category', 'required' => true],
                    'description' => ['type' => 'textarea', 'label' => 'fields.description'],
                    'amount' => ['type' => 'money', 'label' => 'fields.amount', 'required' => true],
                    'payment_method' => ['type' => 'select', 'label' => 'fields.payment_method', 'options' => ['cash', 'bank', 'mobile_banking', 'other']],
                    'reference' => ['type' => 'text', 'label' => 'fields.reference'],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['active', 'void']],
                ],
            ],
            'id-cards' => [
                'table' => 'id_cards',
                'title' => 'modules.id_cards',
                'roles' => ['admin'],
                'fields' => [
                    'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name', 'required' => true],
                    'id_number' => ['type' => 'text', 'label' => 'fields.id_number', 'required' => true],
                    'designation' => ['type' => 'select', 'label' => 'fields.designation', 'options' => ['foreman', 'labor', 'supervisor', 'mistry', 'helper', 'welder', 'engineer'], 'required' => true],
                    'mobile' => ['type' => 'text', 'label' => 'fields.mobile', 'required' => true],
                    'photo_path' => ['type' => 'file', 'label' => 'fields.photo'],
                    'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
                    'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['active', 'deleted'], 'required' => true],
                ],
            ],
            'homepage-sections' => [
                'table' => 'homepage_sections',
                'title' => 'modules.homepage_sections',
                'roles' => ['admin'],
                'fields' => [
                    'section_key' => ['type' => 'select', 'label' => 'fields.section', 'options' => ['hero', 'about', 'contact'], 'required' => true],
                    'title_en' => ['type' => 'text', 'label' => 'fields.title_en', 'required' => true],
                    'title_bn' => ['type' => 'text', 'label' => 'fields.title_bn'],
                    'body_en' => ['type' => 'textarea', 'label' => 'fields.body_en'],
                    'body_bn' => ['type' => 'textarea', 'label' => 'fields.body_bn'],
                    'image_path' => ['type' => 'file', 'label' => 'fields.company_logo'],
                    'sort_order' => ['type' => 'number', 'label' => 'fields.sort_order'],
                    'is_active' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['1', '0'], 'required' => true],
                ],
            ],
            'homepage-updates' => [
                'table' => 'homepage_updates',
                'title' => 'modules.homepage_updates',
                'roles' => ['admin'],
                'fields' => [
                    'title_en' => ['type' => 'text', 'label' => 'fields.title_en', 'required' => true],
                    'title_bn' => ['type' => 'text', 'label' => 'fields.title_bn'],
                    'body_en' => ['type' => 'textarea', 'label' => 'fields.body_en'],
                    'body_bn' => ['type' => 'textarea', 'label' => 'fields.body_bn'],
                    'published_at' => ['type' => 'datetime-local', 'label' => 'fields.published_at'],
                    'image_path' => ['type' => 'file', 'label' => 'fields.photo'],
                    'is_active' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['1', '0'], 'required' => true],
                ],
            ],
            'homepage-services' => [
                'table' => 'homepage_services',
                'title' => 'modules.homepage_services',
                'roles' => ['admin'],
                'fields' => [
                    'title_en' => ['type' => 'text', 'label' => 'fields.title_en', 'required' => true],
                    'title_bn' => ['type' => 'text', 'label' => 'fields.title_bn'],
                    'body_en' => ['type' => 'textarea', 'label' => 'fields.body_en'],
                    'body_bn' => ['type' => 'textarea', 'label' => 'fields.body_bn'],
                    'icon' => ['type' => 'text', 'label' => 'fields.icon'],
                    'sort_order' => ['type' => 'number', 'label' => 'fields.sort_order'],
                    'is_active' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['1', '0'], 'required' => true],
                ],
            ],
            'homepage-media' => [
                'table' => 'homepage_media',
                'title' => 'modules.homepage_media',
                'roles' => ['admin'],
                'fields' => [
                    'media_type' => ['type' => 'select', 'label' => 'fields.media_type', 'options' => ['photo', 'video'], 'required' => true],
                    'title_en' => ['type' => 'text', 'label' => 'fields.title_en', 'required' => true],
                    'title_bn' => ['type' => 'text', 'label' => 'fields.title_bn'],
                    'media_path' => ['type' => 'file', 'label' => 'fields.media', 'required' => true],
                    'thumbnail_path' => ['type' => 'file', 'label' => 'fields.thumbnail'],
                    'sort_order' => ['type' => 'number', 'label' => 'fields.sort_order'],
                    'is_active' => ['type' => 'select', 'label' => 'fields.status', 'options' => ['1', '0'], 'required' => true],
                ],
            ],
            'notifications' => [
                'table' => 'notifications',
                'title' => 'modules.notifications',
                'roles' => ['admin'],
                'creator' => false,
                'fields' => [
                    'user_id' => ['type' => 'relation', 'label' => 'fields.user', 'source' => 'users', 'display' => 'name'],
                    'title_key' => ['type' => 'text', 'label' => 'fields.title_key', 'required' => true],
                    'body_key' => ['type' => 'text', 'label' => 'fields.body_key', 'required' => true],
                    'destination_url' => ['type' => 'text', 'label' => 'fields.destination_url'],
                    'type' => ['type' => 'select', 'label' => 'fields.type', 'options' => ['info', 'success', 'warning', 'danger'], 'required' => true],
                    'is_read' => ['type' => 'select', 'label' => 'fields.is_read', 'options' => ['0', '1'], 'required' => true],
                ],
            ],
            'audit-logs' => [
                'table' => 'audit_logs',
                'title' => 'modules.audit_logs',
                'roles' => ['admin'],
                'read_only' => true,
                'creator' => false,
                'fields' => [
                    'user_id' => ['type' => 'relation', 'label' => 'fields.user', 'source' => 'users', 'display' => 'name'],
                    'action' => ['type' => 'text', 'label' => 'fields.action'],
                    'module' => ['type' => 'text', 'label' => 'fields.module'],
                    'record_id' => ['type' => 'number', 'label' => 'fields.record_id'],
                    'ip_address' => ['type' => 'text', 'label' => 'fields.ip_address'],
                    'user_agent' => ['type' => 'text', 'label' => 'fields.user_agent'],
                    'created_at' => ['type' => 'text', 'label' => 'fields.created_at'],
                ],
            ],
            'login-history' => [
                'table' => 'login_history',
                'title' => 'modules.login_history',
                'roles' => ['admin'],
                'read_only' => true,
                'creator' => false,
                'fields' => [
                    'user_id' => ['type' => 'relation', 'label' => 'fields.user', 'source' => 'users', 'display' => 'name'],
                    'login_identifier' => ['type' => 'text', 'label' => 'fields.login_identifier'],
                    'success' => ['type' => 'select', 'label' => 'fields.success', 'options' => ['0', '1']],
                    'ip_address' => ['type' => 'text', 'label' => 'fields.ip_address'],
                    'user_agent' => ['type' => 'text', 'label' => 'fields.user_agent'],
                    'created_at' => ['type' => 'text', 'label' => 'fields.created_at'],
                ],
            ],
            'settings' => [
                'table' => 'settings',
                'title' => 'modules.settings',
                'roles' => ['admin'],
                'creator' => false,
                'fields' => [
                    'setting_key' => ['type' => 'text', 'label' => 'fields.setting_key', 'required' => true],
                    'setting_value' => ['type' => 'textarea', 'label' => 'fields.setting_value'],
                    'setting_group' => ['type' => 'text', 'label' => 'fields.setting_group', 'required' => true],
                ],
            ],
        ];
    }

    public static function get(string $key): ?array
    {
        return self::all()[$key] ?? null;
    }

    private static function moneyModule(string $table, string $title, array $fieldNames, array $statusOptions, array $roles = ['admin']): array
    {
        $fields = [
            'worker_id' => ['type' => 'relation', 'label' => 'fields.worker', 'source' => 'workers', 'display' => 'full_name', 'required' => true],
            'date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
            'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en'],
            'amount' => ['type' => 'money', 'label' => 'fields.amount', 'required' => true],
            'reason' => ['type' => 'textarea', 'label' => 'fields.reason'],
            'payment_method' => ['type' => 'select', 'label' => 'fields.payment_method', 'options' => ['cash', 'bank', 'mobile_banking', 'other']],
            'reference' => ['type' => 'text', 'label' => 'fields.reference'],
            'description' => ['type' => 'textarea', 'label' => 'fields.description'],
            'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
            'status' => ['type' => 'select', 'label' => 'fields.status', 'options' => $statusOptions, 'required' => true],
        ];
        return [
            'table' => $table,
            'title' => $title,
            'roles' => $roles,
            'financial' => true,
            'fields' => array_intersect_key($fields, array_flip($fieldNames)),
        ];
    }

    private static function expenseModule(string $table, string $title): array
    {
        return [
            'table' => $table,
            'title' => $title,
            'roles' => ['admin', 'foreman'],
            'financial' => true,
            'fields' => [
                'expense_date' => ['type' => 'date', 'label' => 'fields.date', 'required' => true],
                'project_id' => ['type' => 'relation', 'label' => 'fields.project', 'source' => 'projects', 'display' => 'name_en', 'required' => true],
                'category_id' => ['type' => 'relation', 'label' => 'fields.category', 'source' => 'expense_categories', 'display' => 'name_en', 'required' => true],
                'description_en' => ['type' => 'textarea', 'label' => 'fields.description_en'],
                'description_bn' => ['type' => 'textarea', 'label' => 'fields.description_bn'],
                'amount' => ['type' => 'money', 'label' => 'fields.amount', 'required' => true],
                'vendor' => ['type' => 'text', 'label' => 'fields.vendor'],
                'invoice_image' => ['type' => 'file', 'label' => 'fields.invoice_image'],
                'payment_method' => ['type' => 'select', 'label' => 'fields.payment_method', 'options' => ['cash', 'bank', 'mobile_banking', 'other']],
                'notes' => ['type' => 'textarea', 'label' => 'fields.notes'],
            ],
        ];
    }
}
